---
name : Criteo Sponsored Search Conversion Log Dataset
url : http://go.criteo.net/criteo-research-search-conversion.tar.gz
download_filepath: data/external/criteo.tar.gz
extract_filepath: Criteo_Conversion_Search/CriteoSearchData
# filepath_raw must be joined with the data directory for the current lab
destination: data/raw/criteo.csv
sep : \t
missing: -1