---
name : Criteo Sponsored Search Conversion Log Dataset
source : http://go.criteo.net/criteo-research-search-conversion.tar.gz
destination: data/criteo/external/criteo.tar.gz
filepath_extract: Criteo_Conversion_Search/CriteoSearchData
filepath_raw: data/criteo/raw/criteo.csv
workspace: root
sep : \t
missing: -1