---
name : Criteo Sponsored Search Conversion Log Dataset
url : http://go.criteo.net/criteo-research-search-conversion.tar.gz
destination: data/criteo/external/criteo.tar.gz
filepath_compressed : data/criteo/external/criteo.tar.gz
filepath_decompressed : data/criteo/external/Criteo_Conversion_Search/CriteoSearchData
filepath_raw: data/criteo/raw/criteo.csv
filepath_staged: data/criteo/staged/criteo.pkl
sep : \t
missing: -1
